name: Ship js trigger
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: Checkout master branch
        run: git switch master
      - name: Install dependencies
        run: yarn install
      - name: Ship.js Trigger
        run: npm run release:trigger
        env: # https://shipjs.netlify.com/guide/getting-started.html#setup-github-actions
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          SLACK_INCOMING_HOOK: ${{ secrets.SLACK_INCOMING_HOOK }}
